# Generated by Django 4.0.1 on 2022-02-02 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0002_remove_resume_country_code_alter_resume_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='cv_template',
            field=models.CharField(default='Casual', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resume',
            name='name',
            field=models.CharField(default='Casual', max_length=100),
        ),
    ]
