# Generated by Django 4.0.1 on 2022-02-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0003_resume_cv_template_alter_resume_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='career_objective',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='education',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='experience',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='hobbies',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='resume',
            name='skills',
            field=models.TextField(blank=True),
        ),
    ]
